### ISSUE TITLE
白色的圆点如何不随着手势滑动而移动？

### ISSUE THREAD

**Issue by MIkeeJY** [wanglu1209/Banner#2]
并且那个白色选中选点位置计算不准确在nexus4的手机 会跑到左边

**Comment by wanglu1209** [comment]
是的，我也发现这个问题了，以前是没问题的，我也没改代码不知道为什么现在变成这样了。我这周弄一下，到时候再联系你。谢谢你的回复

**Comment by wanglu1209** [comment]
白色选中原点位置已经弄好，不随着手势滑动而滑动这个目前没有，因为设计写这个的时候就是这样的，后期可加，谢谢
